# Site settings
title: RODFactory
email: rodfactory@gmail.com
description: One stop for all the fun!
baseurl: "/rodfactory"
url: "http://chettyarun.github.io/rodfactory" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
